Repository osu-tournament-rating/otr-wiki, pull requests merged in 2024-03, with the labels that each got.

#23 Fix missing color for label
  contribution/labels/en.md
Labels: size/XS

#20 Create README & update folder structures
  api/README.md
  api/authorization/en.md
  api/development/setup/en.md
  api/usage/authorization/en.md
  api/usage/scopes/en.md
Labels: type:documentation, size/M

#16 Initial proposal for visual redesign
  README.md
  api/README.md
  api/changelog/en.md
  api/usage/endpoints/beatmaps/en.md
  api/usage/endpoints/en.md
  api/usage/endpoints/matches/en.md
  api/usage/endpoints/players/en.md
  api/usage/objects/en.md
  contribution/README.md
  contribution/contributors/en.md
Labels: size/XXL

#24 Add API styling
  api/README.md
  api/development/styling/en.md
Labels: type:documentation, size/S, type:code-quality

#27 Fix typo in tournaments.md
  algorithm/tournaments.md
Labels: size/XS

#28 Update api styling doc
  api/development/styling/en.md
Labels: type:documentation, size/S

#25 OAuth documentation
  api/authorization/en.md
  api/usage/authorization/en.md
  api/usage/endpoints/en.md
  api/usage/endpoints/oauth/en.md
  api/usage/limits/en.md
  api/usage/objects/en.md
Labels: type:documentation, size/L
